global {
  debug-level = 1
  user = root
  group = root
  pidfile = "/var/run/scanbd/scanbd.pid"
  timeout = 500

  environment {
    device = "SCANBD_DEVICE"
    action = "SCANBD_ACTION"
  }

  scriptdir = /etc/scanbd/scripts

  # scanbd auto-loads device configs from <etcdir>/scanner.d/*.conf
  etcdir = /etc/scanbd
}
